In [38]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [39]:
#complex json file structure so we need to normalize first as read csv cannot read
import json
with open('weather_forecast.json') as f:
    data=json.load(f)

In [40]:
weather1=pd.json_normalize(data,record_path='list',sep='_').drop(columns='weather')
weather_1

,dt,sunrise,sunset,pressure,humidity,speed,deg,gust,clouds,pop,temp_day,temp_min,temp_max,temp_night,temp_eve,temp_morn,feels_like_day,feels_like_night,feels_like_eve,feels_like_morn
0,1641463200,1641444707,1641481757,1021,48,2.92,59,4.11,0,0,292.57,285.16,292.73,287.90,291.59,285.33,291.82,287.18,290.51,284.48
1,1641549600,1641531113,1641568203,1018,42,2.45,221,2.65,0,0,291.55,285.69,293.35,287.99,291.11,285.83,290.54,286.78,289.88,285.22
2,1641636000,1641617517,1641654650,1016,28,3.25,149,4.45,49,0,292.11,286.65,295.53,290.85,294.11,286.65,290.79,289.33,292.78,285.31
3,1641722400,1641703919,1641741097,1015,40,7.21,224,11.98,1,0,289.97,286.46,291.87,287.73,290.21,287.58,288.75,286.24,288.60,285.86
4,1641808800,1641790320,1641827546,1014,33,8.74,214,11.93,0,0,288.71,284.47,290.27,286.41,289.45,284.57,287.18,285.15,288.00,283.07
5,1641895200,1641876719,1641913994,1017,38,8.00,195,11.20,0,0,289.48,284.61,292.73,287.52,291.67,284.61,288.16,285.82,290.23,283.40
6,1641981600,1641963116,1642000444,1019,23,4.11,184,7.51,100,0,290.17,285.65,292.95,287.79,291.58,285.65,288.53,286.41,290.24,283.87

In [42]:
weather_2=pd.json_normalize(data,record_path=['list','weather'],meta=[['list','dt']]).drop_duplicates(subset='list.dt').reset_index(drop=True)
weather_2

    id    main       description icon     list.dt
0  800   Clear      sky is clear  01d  1641463200
1  800   Clear      sky is clear  01d  1641549600
2  802  Clouds  scattered clouds  03d  1641636000
3  800   Clear      sky is clear  01d  1641722400
4  800   Clear      sky is clear  01d  1641808800
5  800   Clear      sky is clear  01d  1641895200
6  804  Clouds   overcast clouds  04d  1641981600

In [45]:
weather=pd.concat([weather_1,weather_2],axis=1).drop(columns='list.dt')
weather

,dt,sunrise,sunset,pressure,humidity,speed,deg,gust,clouds,pop,temp_day,temp_min,temp_max,temp_night,temp_eve,temp_morn,feels_like_day,feels_like_night,feels_like_eve,feels_like_morn,id,main,description,icon
0,1641463200,1641444707,1641481757,1021,48,2.92,59,4.11,0,0,292.57,285.16,292.73,287.90,291.59,285.33,291.82,287.18,290.51,284.48,800,Clear,sky is clear,01d
1,1641549600,1641531113,1641568203,1018,42,2.45,221,2.65,0,0,291.55,285.69,293.35,287.99,291.11,285.83,290.54,286.78,289.88,285.22,800,Clear,sky is clear,01d
2,1641636000,1641617517,1641654650,1016,28,3.25,149,4.45,49,0,292.11,286.65,295.53,290.85,294.11,286.65,290.79,289.33,292.78,285.31,802,Clouds,scattered clouds,03d
3,1641722400,1641703919,1641741097,1015,40,7.21,224,11.98,1,0,289.97,286.46,291.87,287.73,290.21,287.58,288.75,286.24,288.60,285.86,800,Clear,sky is clear,01d
4,1641808800,1641790320,1641827546,1014,33,8.74,214,11.93,0,0,288.71,284.47,290.27,286.41,289.45,284.57,287.18,285.15,288.00,283.07,800,Clear,sky is clear,01d
5,1641895200,1641876719,1641913994,1017,38,8.00,195,11.20,0,0,289.48,284.61,292.73,287.52,291.67,284.61,288.16,285.82,290.23,283.40,800,Clear,sky is clear,01d
6,1641981600,1641963116,1642000444,1019,23,4.11,184,7.51,100,0,290.17,285.65,292.95,287.79,291.58,285.65,288.53,286.41,290.24,283.87,804,Clouds,overcast clouds,04d